"use client";

import Image from "next/image";

const projects = [
  { title: "QADIS", category: "Quantum ML / Security", description: "A hybrid quantum-classical anomaly detection system for high-dimensional security data, built with Qiskit and PennyLane.", tags: ["Python", "Qiskit", "PennyLane"], image: "/projects/qadis.png", live: "https://qadis.vercel.app", code: "https://github.com/techtribe01/Quantum_machine_Learning" },
  { title: "EyesTalk", category: "BCI / Signal Processing", description: "An EOG-based brain-computer interface that translates eye blinks into reliable computer control with roughly 96% classification accuracy.", tags: ["Python", "EOG", "Neurotech"], image: "/projects/eyestalk.png", live: "https://eyestalk3.vercel.app/", code: "https://github.com/techtribe01/eyetalk3" },
  { title: "Skillarion", category: "Full-stack Product", description: "A production marketing platform delivered with Next.js, TypeScript, Tailwind, motion, validation, and API integrations.", tags: ["Next.js", "TypeScript", "Tailwind"], image: "/projects/skillarion.png", live: "https://skillariondevelopment.netlify.app", code: "https://github.com/techtribe01/skillarion" },
  { title: "C Coin", category: "Web3 / Smart Contracts", description: "A transparent campus currency concept for peer-to-peer micro-transfers and auditable decentralized transactions.", tags: ["Solidity", "Ethereum", "Web3"], image: "/projects/ccoin.png", live: "https://c-coin.vercel.app", code: "https://github.com/techtribe01/c2coin" },
];

export default function Projects() {
  return <section id="projects" className="bg-background px-6 py-28 text-foreground md:px-10 lg:px-16"><div className="mx-auto max-w-7xl"><div className="mb-14 flex flex-col justify-between gap-6 border-b border-border pb-8 md:flex-row md:items-end"><div><p className="eyebrow">02 / Selected work</p><h2 className="mt-5 font-sans text-5xl font-semibold tracking-[-0.06em] md:text-7xl">Built to be useful.</h2></div><p className="max-w-sm text-sm leading-relaxed text-muted-foreground">A selection of systems, products, and experiments across the AI engineering stack.</p></div><div className="grid gap-6 md:grid-cols-2">{projects.map((project, index) => <article key={project.title} className="group overflow-hidden rounded-2xl border border-border bg-card transition-colors hover:border-primary/60"><div className="relative aspect-[16/10] overflow-hidden border-b border-border"><Image src={project.image} alt={`${project.title} project preview`} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 50vw" /><div className="absolute left-4 top-4 rounded-full bg-background/90 px-3 py-1 font-mono text-[10px] uppercase tracking-wider text-primary">0{index + 1} / {project.category}</div></div><div className="p-6 md:p-8"><div className="flex items-start justify-between gap-4"><h3 className="text-2xl font-semibold tracking-tight">{project.title}</h3><div className="flex gap-3 text-sm font-mono text-muted-foreground"><a href={project.code} target="_blank" rel="noopener noreferrer" aria-label={`View ${project.title} source code`} className="hover:text-primary">CODE</a><a href={project.live} target="_blank" rel="noopener noreferrer" aria-label={`View ${project.title} live demo`} className="hover:text-primary">LIVE</a></div></div><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{project.description}</p><div className="mt-6 flex flex-wrap gap-2">{project.tags.map((tag) => <span key={tag} className="rounded-full border border-border px-3 py-1 font-mono text-[11px] text-muted-foreground">{tag}</span>)}</div></div></article>)}</div></div></section>;
}
